from core.failure import Failure


class NumParsFailure(Failure):
    error_message = "Пришла ошибка конкретная"